# Custom Language File for Launcher Customizer

[ejs.app]
title = "Nyangfarm"

[ejs.landing]
mediaGitHubURL = "https://github.com/jay6977/Nyangfarm"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zcjDyEw"

[ejs.settings]
sourceGithubLink = "https://github.com/jay6977/Nyangfarm"
supportLink = "https://github.com/jay6977/Nyangfarm/issues"

[ejs.welcome]
welcomeHeader = "냥팜에 오신 것을 환영합니다!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
